sudo: false

language: c

cache:
  directories:
  - $HOME/.stack

# GHC depends on GMP.
addons:
  apt:
    packages:
    - libgmp-dev

env:
- ARGS=""

before_install:
- export LANG=en_US.UTF-8
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script: stack $ARGS --no-terminal --install-ghc test
